# -*- coding: utf-8 -*-
"""Face Emotion Detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bIKwlH7VFUAMW-jul6PfoCpwAxEckRJE
"""

pip install opencv-python

pip install opencv-contrib-python

import cv2

pip install deepface

from deepface import DeepFace

pip install matplotlib

import matplotlib.pyplot as plt

img= cv2.imread('/content/happy.jpeg')

plt.imshow(img)

plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))

predictions=DeepFace.analyze(img)

predictions

type(predictions)

predictions[0]['dominant_emotion']

faceCascade=cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_default.xml')

gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces=faceCascade.detectMultiScale(gray,1.1,4)
for(x,y,w,h) in faces:
  cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),10)

plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))

font=cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(img,
            predictions[0]['dominant_emotion'],
            (50,100),
            font,2,
            (0,0,255),
            3,
            cv2.LINE_4);

plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))